### ISSUE TITLE
ERROR: UndefVarError: axpy! not defined

### ISSUE THREAD

**Issue by woodenleaves** [vincentarelbundock/QuantileRegression.jl#12]
I tried to run the example code and find that there is such an error:

julia> ResultQR = qreg(foodexp~income, Data, .5)

ERROR: UndefVarError: axpy! not defined
 in qreg_ip_coef(::Array{Float64,1}, ::Array{Float64,2}, ::Float64) at /home/potato/.julia/v0.5/QuantileRegression/src/InteriorPoint.jl:61
 in #qreg#2(::Symbol, ::Function, ::DataFrames.Formula, ::DataFrames.DataFrame, ::Float64) at /home/potato/.julia/v0.5/QuantileRegression/src/QuantileRegression.jl:27
 in qreg(::DataFrames.Formula, ::DataFrames.DataFrame, ::Float64) at /home/potato/.julia/v0.5/QuantileRegression/src/QuantileRegression.jl:21

**Comment by vincentarelbundock** [comment]
Package is no longer supported. See amended README file.

**Comment by pkofod** [comment]
@woodenleaves thanks for the report. This repo will be transferred to my account, and before long, I will have it polished and shining again.

**Comment by woodenleaves** [comment]
@pkofod Thanks a lot!!!

**Comment by pkofod** [comment]
@woodenleaves it is fixed now, I'll continue making some changes, and then I'll officially tag it in metadata
