### ISSUE TITLE
Further development of Quantile Regression

### ISSUE THREAD

**Issue by pkofod** [vincentarelbundock/QuantileRegression.jl#3]
As far as I understand, this package was started as a go "let me try Julia"-project at the hands of @vincentarelbundock . I do think that we should have a good implementation of quantile regression in Julia, so this "Issue" is really a question: how can we improve QuantileRegression.jl? I will collect points and suggestions in this post.

1) Go through syntax to make sure that it is consistent with other statistics packages. Example: as suggested in https://github.com/JuliaStats/Roadmap.jl/issues/1, it is preferable to use maxiter if everyone else does - we use max_iter.

**Comment by vincentarelbundock** [comment]
1. If this request stays here, I fear that nobody will read it. If you're interested in making big improvements, a mailing list post is probably appropriate.
2. Would you like to be added as a contributor to the repo so you can accept pull requests?

**Comment by pkofod** [comment]
1) I think you're right, its probably better to post at julia-*, but I actually think it's also great to have some of the "future plans/roadmap"-information available here as well. Even if it means "duplicate" posts.

2) That would be great.

**Comment by vincentarelbundock** [comment]
OK, added you so you should be able to push to repo directly. Thanks again.

**Comment by vincentarelbundock** [comment]
Package is no longer supported. See amended README file.

**Comment by pkofod** [comment]
This is tagged in metadata right? If you want you can transfer the repo to me. Then I'll fix it up for latest Julia, and github can automatically handle the move by redirecting

**Comment by vincentarelbundock** [comment]
Good idea, thanks

**Comment by vincentarelbundock** [comment]
doesn't work because you already have a repo of that name

**Comment by pkofod** [comment]
I'll delete it

**Comment by pkofod** [comment]
The request expired... can you try again ? :)

**Comment by vincentarelbundock** [comment]
i just retried

**Comment by pkofod** [comment]
Perfect, it worked.
