### ISSUE TITLE
An interior point method

### ISSUE THREAD

**Issue by pkofod** [vincentarelbundock/QuantileRegression.jl#4]
It seems as if the current algorithm might be a bit slow for problems with "many" explanatory variables. I was trying to mimick a project run on multiple millions of observations, with 40'ish variables. Timings are below for a small number of observations.
![results](https://cloud.githubusercontent.com/assets/8431156/6684924/fc529bc2-cc95-11e4-9854-a2e010c48baf.png)

I can't really explain the dips using the original algorithms. Luck? The mean is over 10 runs. The difference in trajectories seem to increase with more variables, and for few explanatory variables, the least squares method seems to dominate (figures not shown). With more testing, it might be possible to make qreg a hybrid-algorithm based of a combination of rows and columns in the design matrix,  with the option to manually select an algorithm.

Free lunch? Not so much. The IP-algorithm currently uses between 30 and 150 times as much memory. I am trying to optimize the code atm.
![results_mem](https://cloud.githubusercontent.com/assets/8431156/6688854/e1b7fc00-ccb6-11e4-96d7-38c9e0f3dd69.png)

Edit:

I not have _some_ numbers regarding larger scale problems (still <<1,000,000). Data points are at 200, 40200, 80200, 120200, 160200, 20200 observations. This time mean of 15 replications. Obviously, it is not enough to "even out" background noise, but it gives an idea.

![results_time](https://cloud.githubusercontent.com/assets/8431156/6697606/0a0bf446-ccf2-11e4-979c-ae53be8ec480.png)

![results_mem](https://cloud.githubusercontent.com/assets/8431156/6697650/550d0840-ccf2-11e4-9ad5-a5a775aede3e.png)

Edit 2: 
Even more evidence (getting repetitive here...), now up to 2*10^6 observations.
![results_time](https://cloud.githubusercontent.com/assets/8431156/6706757/d8368e30-cd60-11e4-9516-3d1fa8ed89c4.png)

![results_mem](https://cloud.githubusercontent.com/assets/8431156/6706759/df8acb88-cd60-11e4-8e18-803310e34abe.png)

(by the way, I'm really loving the standard output from Winston!)

**Comment by pkofod** [comment]
Tried with 20 explanatory variables, and the picture looks identical.
![results_time_2](https://cloud.githubusercontent.com/assets/8431156/7252479/ba469d8a-e835-11e4-984e-c9346b06a0db.png)

Maybe there is room for improvement for the IRLS-algorithm, but currently I would prefer IP as the standard implementation. I have not checked even smaller models, maybe I should. 

I still do not understand the very low "minimum" times for IRLS. All runs for a given number of observations are run with the same data set, so it is kind of baffling to me. I have to find out what the estimates from the very fast runs are.

**Comment by vincentarelbundock** [comment]
Very nice! The code is very readable and nicely commented. Are we sure it's OK to publish this given the original license? 

    # A Frisch-Newton algorithm as described in http://projecteuclid.org/euclid.ss/1030037960
    # qreg_ip_coef is a modified lp_fnm of Daniel Morillo & Roger Koenker
    # Translated from Ox to Matlab by Paul Eilers 1999
    # Modified by Roger Koenker 2000
    # More changes by Paul Eilers 2004
    # QuantileRegression.jl developers 2015

**Comment by pkofod** [comment]
I will look more into the original licensing, and see if we're good or not. The original code is by Koenker, and can be redistributed for non-commercial use ( http://www.econ.uiuc.edu/~roger/research/rqn/rqn.html ). See also http://www.econ.uiuc.edu/~roger/research/rqn/rqn.s and http://www.econ.uiuc.edu/~roger/research/rqn/rqn.b for the original code. There is no further licensing information, but I will contact Koenker.

**Comment by vincentarelbundock** [comment]
Right. One potential issue with this is the "non-commercial" purpose. So we might need a different license than BSD3 for this specific file. 

Arrrrggh! I hate those licensing issues.

**Comment by pkofod** [comment]
Solved in #7
